# Generated by Django 4.2 on 2023-06-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_student_teacher_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product')),
                ('cost', models.IntegerField(default=10)),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('inventory', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True, verbose_name='availability status')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(default=['empty cart'], to='products.products')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student', verbose_name='student user')),
            ],
        ),
    ]
