# Generated by Django 4.2 on 2023-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=10)),
                ('category', models.CharField(max_length=100)),
                ('inventory', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True, verbose_name='availability status')),
            ],
        ),
    ]
